quarkus.datasource.db-kind=h2
quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.hibernate-orm.log.sql=true

quarkus.http.default-produces=application/json
quarkus.http.default-consumes=application/json


